#!/bin/sh

ip link set dev "can0" down && ip link set "can0" type can bitrate 1000000 && ip link set dev "can0" up
ip link set dev "can1" down && ip link set "can1" type can bitrate 1000000 && ip link set dev "can1" up
